---
title: "Data Visualization Final Project - Chicago Violence, SVI and Social Metrics"
author: "Salvatore 'Sal' Macchione and Harry Franklin"
date: "March 09, 2026"
format: 
  pdf:
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
include-before-body:
  text: |
    \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaksymbolleft={},
      breaklines
    }
output:
  echo: false
  eval: false
execute:
  echo: false
  warning: false
  message: false
---
# Github Usernames: smacchione, hmfranklin14
# Lecture Section: M/W 9 - 10:20am
# Introduction, Background and Research Question

From the notorious mob violence of the 1920s to the predominantly gang-related crime of today, Chicago has long been grappling with violent crime. Though crime has overall declined over the last several years, the city still makes regional and national headlines — justifiably or not — for its relatively high rates of violence. Though many analyses and dissections of crime in Chicago have been done, there exists a gap in existing data as it pertains to three key questions: 
- How effective are social vulnerability, mental, and developmental factors in predicting crime across Chicago?
- To what degree is the Social Vulnerability Index (SVI) geographically correlated with violent crime rates across the city?
- How accurate are self-reported statistics vs more objective values in predicting crime rates?

In this regard, our project examines the relationship between violent crime and social vulnerability across Chicago neighborhoods using data from the Center for Disease Control and Prevention (CDC), the Chicago Health Atlas, and the Chicago Police Department's Citizen Law Enforcement Analysis and Reporting (CLEAR) database. More specifically, we ask whether violent crime rates are systematically higher in census tracts and zip codes with greater social vulnerability, and whether that relationship becomes especially pronounced at the upper end of the vulnerability distribution. We also explore how related ZIP-code-level public health and hardship measures align with these spatial patterns in our Streamlit application. In doing so, we aim to shed light on how to better target anti-crime and anti-poverty interventions, and how to best utilize existing measures to predict crime and allocate resources.

# SVI and Crime in Chicago
We first combined incident-level violent crime data for Chicago from 2021–2025 with census-tract SVI values and population data to examine how crime varies across geographies. After cleaning and standardizing the data, we converted crime dates into a monthly time series and merged tract-level measures to enable geographic comparisons. Given that geographies have varying populations (and thus make it so raw crime incidence can't be directly compares), we focused primarily on population-adjusted measures, calculating annualized and monthly violent crime rates per 1,000 residents. To analyze how vulnerability relates to crime, we first grouped tracts into standard SVI quintiles and then created additional upper-tail bins (81–95, 95–98, 98–99, and 99+) to better capture variation among the most socially vulnerable areas and determine whether the most vulnerable populations disproportionatly commit more violent crime (thus skewing the top quintile). 

## Figure 1: 
```{python}
#echo: false
#eval: true

#libraries and plugins
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import altair as alt 
import os
import seaborn as sns 
import geopandas as gpd
from shapely.geometry import Point
import json
from pathlib import Path


#settings
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

#extra settings
import warnings 
warnings.filterwarnings('ignore')
alt.renderers.enable("png")
alt.data_transformers.disable_max_rows()

import tempfile 
from IPython.display import SVG, display, Image
import vl_convert as vlc

def display_altair_png(chart, scale=2):
    """
    Render an Altair chart to a PNG and display it inline.

    Parameters
    ----------
    chart : altair.Chart
        Altair chart object to render.
    scale : int, optional
        Resolution scaling factor for the PNG (default = 2). Use scale=2 for standard slides. Use scale = 3–4 for dense figures or PDF exports.
    """
    png_bytes = vlc.vegalite_to_png(chart.to_dict(), scale=scale)

    # Write to a temporary PNG file and display
    with tempfile.NamedTemporaryFile(suffix=".png") as tmp:
        tmp.write(png_bytes)
        tmp.flush()
        display(Image(filename=tmp.name))

#additional cleaning and adjustments
BASE_PATH = Path(__file__).resolve().parent
while not (BASE_PATH / "data").exists():
    BASE_PATH = BASE_PATH.parent
    
crime = pd.read_csv(os.path.join(base_path, "data/derived-data/crime_svi_merge_no_na.csv"))
tracts = gpd.read_file(os.path.join(base_path, "data/raw-data/Census_Tracts_20260228/geo_export_89c4b171-2783-4715-9b7d-e49f753f00f0.shp"))
crimes_with_tracts = gpd.read_file(os.path.join(base_path, "data/derived-data/crimes_with_tracts.csv"))
tract_full = gpd.read_file(os.path.join(base_path, "data/derived-data/tract_full.geojson"))

#adding and fixing date(s)
crime["Date"] = pd.to_datetime(crime["Date"], errors="coerce")
crime["month"] = crime["Date"].dt.to_period("M").dt.to_timestamp()

#adding quintiles for SVI and in tract_full 
crime["SVI_quintile"] = pd.cut(
    crime["SVI"],
    bins=[0, 0.2, 0.4, 0.6, 0.8, 1.0],
    labels=["1", "2", "3", "4", "5"],
    include_lowest=True)

#tract full 
tract_full["SVI_quintile"] = pd.cut(
    tract_full["svi"],
    bins=[0, 0.2, 0.4, 0.6, 0.8, 1.0],
    labels=["1", "2", "3", "4", "5"],
    include_lowest=False)
#replace NA with 0 that are ignored
tract_full["pop"] = tract_full["pop"].fillna(0)

crime = crime.dropna(subset=["SVI_quintile"])
pop_by_q_full = (
    tract_full.dropna(subset=["pop", "SVI_quintile"])
              .groupby("SVI_quintile", as_index=False, observed=True)
              .agg(pop=("pop", "sum")))
crime_q = (
    crime.dropna(subset=["SVI_quintile"])
         .groupby("SVI_quintile", as_index=False, observed=True)
         .agg(incidents=("ID", "count")))

incidents_per_month_q = (
    crime.dropna(subset=["month", "SVI_quintile"])
        .groupby(["month", "SVI_quintile"], as_index=False, observed=True)
        .agg(incidents=("ID", "count")))
incidents_per_month_q = incidents_per_month_q.merge(pop_by_q_full, on="SVI_quintile", how="left")
incidents_per_month_q["incidents_per_1000"] = (incidents_per_month_q["incidents"] / incidents_per_month_q["pop"]) * 1000
incidents_over_time = alt.Chart(incidents_per_month_q).mark_line().encode(
    x=alt.X("month:T", title="Month"),
    y=alt.Y("incidents_per_1000:Q", title="Incidents per 1,000 residents (monthly)"),
           color=alt.Color(
            "SVI_quintile:N",
            title="SVI Ranges, Least to Most Vulnerable",
            sort=["1","2","3","4","5"],
            scale=alt.Scale(scheme="tealblues"))).properties(
    title="Reported Violent Crimes per Capita Over Time by SVI Quintile, Chicago, 2021–2025",
    width=700,
    height=500)
display_altair_png(incidents_over_time)
```

## Figure 2: 